services:
  db-askend:
    image: postgres:17.0-alpine3.20
    container_name: database-askend-filters
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  backend-application:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=local-postgres
    depends_on:
      - db-askend
